version: '3.8'
services:
  odoo-dev:
    image: odoo:17.0
    ports: ["8069:8069"]
    environment:
      - HOST=db-dev
      - USER=odoo
      - PASSWORD=odoo
    depends_on: ["db-dev"]
  db-dev:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes: ["odoo-dev-data:/var/lib/postgresql/data"]
volumes:
  odoo-dev-data:
